#!/usr/bin/env bash
#Configure HAproxy to automatically redirect HTTP traffic to HTTPS.

frontend www-http
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend www-https
    bind *:443 ssl crt /etc/letsencrypt/live/www.<your_domain>/fullchain.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend www-backend

backend www-backend
    server webserver <your_web_server_ip>:80
