#!/usr/bin/env bash
#configures a Nginz server to listen to port 80

#creates a symbolic link [-s option] between the Nginx configuration file
#and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginz
service nginx start
#terminates the first nginx process
kill "$(pgrep 'nginx' | head -1)"
