#!/usr/bin/env bash

# Configure Nginx to run as the nginx user
useradd -r -M nginx 
# Create user nginx

# Set ownership of Nginx directories to nginx user
chown -R nginx:nginx /etc/nginx /var/lib/nginx

# Update Nginx configuration
sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf

# Grant permissions for Nginx user to access configuration files
chmod 644 /etc/nginx/nginx.conf /etc/nginx/conf.d/*.conf

# Listen on all active IPs on port 8080
sed -i 's/listen 80;/listen 0.0.0.0:8080;/' /etc/nginx/nginx.conf

# Restart Nginx with the new configuration
service nginx restart
